<?php

return [
    [
        "id" => "1",
        "name" => "Il Padrino",
        "name_en" => "The Godfather",
        "locality" => "american",
        "date" => "1972-03-24",
        "vote" => "9.2",
        "thumb" => "https://pad.mymovies.it/filmclub/2002/08/056/locandina.jpg",
    ],
    [
        "id" => "2",
        "name" => "Via Col Vento",
        "name_en" => "Gone With The Wind",
        "locality" => "american",
        "date" => "1939-12-15",
        "vote" => "8.6",
        "thumb" => "https://cultura.biografieonline.it/wp-content/uploads/2012/09/Via-col-vento.jpg",
    ],
    [
        "id" => "3",
        "name" => "Psycho",
        "name_en" => "Psycho",
        "locality" => "american",
        "date" => "1960-06-16",
        "vote" => "9.4",
        "thumb" => "https://m.media-amazon.com/images/I/51FBYO9TDPL._AC_UF894,1000_QL80_.jpg",
    ],
    [
        "id" => "4",
        "name" => "Gravity",
        "name_en" => "Gravity",
        "locality" => "american/british",
        "date" => "2013-08-28",
        "vote" => "7.8",
        "thumb" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncypkwObSDEJeNVQPmTt3uiJ6Waq1WnO4cdfPonW8rfm4vqYddNmmDhIeG4tIFxnkZ58&usqp=CAU",
    ],
    [
        "id" => "5",
        "name" => "Toy Story - Il Mondo Dei Giocattoli",
        "name_en" => "Toy Story",
        "locality" => "american/british",
        "date" => "1995-11-19",
        "vote" => "9.0",
        "thumb" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWogft9PN3FOq8SNmydPPiI_byNTWEWp-RsQ&usqp=CAU",
    ],
    [
        "id" => "6",
        "name" => "Pulp Fiction",
        "name_en" => "Pulp Fiction",
        "locality" => "american",
        "date" => "1994-10-14",
        "vote" => "9.2",
        "thumb" => "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    ],
    [
        "id" => "7",
        "name" => "Forrest Gump",
        "name_en" => "Forrest Gump",
        "locality" => "american/british",
        "date" => "1994-06-23",
        "vote" => "8.8",
        "thumb" => "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    ],
    [
        "id" => "8",
        "name" => "Guerre Stellari",
        "name_en" => "Star Wars",
        "locality" => "american",
        "date" => "1977-05-25",
        "vote" => "8.6",
        "thumb" => "https://m.media-amazon.com/images/I/51kmNBe80yL._AC_UF894,1000_QL80_.jpg",
    ],
    [
        "id" => "9",
        "name" => "E.T. - L'extra-terrestre",
        "name_en" => "E.T. The Extra-Terrestrial",
        "locality" => "american",
        "date" => "1982-05-26",
        "vote" => "7.9",
        "thumb" => "https://www.ibs.it/images/5053083001780_0_424_0_75.jpg",
    ],
    [
        "id" => "10",
        "name" => "Il silenzio degli innocenti",
        "name_en" => "The Silence of the Lambs",
        "locality" => "american",
        "date" => "1991-01-30",
        "vote" => "8.6",
        "thumb" => "https://pad.mymovies.it/filmclub/2006/08/058/locandina.jpg",
    ],
];
